package com.shinowit.dao.mapper;

import com.shinowit.entity.TbaDeliveryinfo;
import com.shinowit.entity.TbaDeliveryinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbaDeliveryinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Mon Jan 05 10:26:01 CST 2015
     */
    int countByExample(TbaDeliveryinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Mon Jan 05 10:26:01 CST 2015
     */
    int deleteByExample(TbaDeliveryinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Mon Jan 05 10:26:01 CST 2015
     */
    int deleteByPrimaryKey(String deliveryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Mon Jan 05 10:26:01 CST 2015
     */
    int insert(TbaDeliveryinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Mon Jan 05 10:26:01 CST 2015
     */
    int insertSelective(TbaDeliveryinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Mon Jan 05 10:26:01 CST 2015
     */
    List<TbaDeliveryinfo> selectByExample(TbaDeliveryinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Mon Jan 05 10:26:01 CST 2015
     */
    TbaDeliveryinfo selectByPrimaryKey(String deliveryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Mon Jan 05 10:26:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbaDeliveryinfo record, @Param("example") TbaDeliveryinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Mon Jan 05 10:26:01 CST 2015
     */
    int updateByExample(@Param("record") TbaDeliveryinfo record, @Param("example") TbaDeliveryinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Mon Jan 05 10:26:01 CST 2015
     */
    int updateByPrimaryKeySelective(TbaDeliveryinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Mon Jan 05 10:26:01 CST 2015
     */
    int updateByPrimaryKey(TbaDeliveryinfo record);

    List<TbaDeliveryinfo> selectPage(TbaDeliveryinfoCriteria example);

    String selectMaxPrimaryKeyValue();
}