package com.shinowit.dao.mapper;

import com.shinowit.entity.TbaMemberinfo;
import com.shinowit.entity.TbaMemberinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbaMemberinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int countByExample(TbaMemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int deleteByExample(TbaMemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int insert(TbaMemberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int insertSelective(TbaMemberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    List<TbaMemberinfo> selectByExample(TbaMemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    TbaMemberinfo selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByExampleSelective(@Param("record") TbaMemberinfo record, @Param("example") TbaMemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByExample(@Param("record") TbaMemberinfo record, @Param("example") TbaMemberinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByPrimaryKeySelective(TbaMemberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByPrimaryKey(TbaMemberinfo record);

    List<TbaMemberinfo> selectPage(TbaMemberinfoCriteria example);

    String selectMaxPrimaryKeyValue();
}