package com.shinowit.dao.mapper;

import com.shinowit.entity.TmeMerchandiseinfo;
import com.shinowit.entity.TmeMerchandiseinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmeMerchandiseinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_MerchandiseInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int countByExample(TmeMerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_MerchandiseInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int deleteByExample(TmeMerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_MerchandiseInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int deleteByPrimaryKey(Integer merchandiseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_MerchandiseInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int insert(TmeMerchandiseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_MerchandiseInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int insertSelective(TmeMerchandiseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_MerchandiseInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    List<TmeMerchandiseinfo> selectByExample(TmeMerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_MerchandiseInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    TmeMerchandiseinfo selectByPrimaryKey(Integer merchandiseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_MerchandiseInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByExampleSelective(@Param("record") TmeMerchandiseinfo record, @Param("example") TmeMerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_MerchandiseInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByExample(@Param("record") TmeMerchandiseinfo record, @Param("example") TmeMerchandiseinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_MerchandiseInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByPrimaryKeySelective(TmeMerchandiseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_MerchandiseInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByPrimaryKey(TmeMerchandiseinfo record);

    List<TmeMerchandiseinfo> selectPage(TmeMerchandiseinfoCriteria example);

    Integer selectMaxPrimaryKeyValue();
}