package com.shinowit.dao.mapper;

import com.shinowit.entity.TmeOutstockinfo;
import com.shinowit.entity.TmeOutstockinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmeOutstockinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OutStockInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int countByExample(TmeOutstockinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OutStockInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int deleteByExample(TmeOutstockinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OutStockInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int deleteByPrimaryKey(Integer outbillcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OutStockInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int insert(TmeOutstockinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OutStockInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int insertSelective(TmeOutstockinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OutStockInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    List<TmeOutstockinfo> selectByExample(TmeOutstockinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OutStockInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    TmeOutstockinfo selectByPrimaryKey(Integer outbillcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OutStockInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByExampleSelective(@Param("record") TmeOutstockinfo record, @Param("example") TmeOutstockinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OutStockInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByExample(@Param("record") TmeOutstockinfo record, @Param("example") TmeOutstockinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OutStockInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByPrimaryKeySelective(TmeOutstockinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OutStockInfo
     *
     * @mbggenerated Thu Dec 25 15:00:55 CST 2014
     */
    int updateByPrimaryKey(TmeOutstockinfo record);

    List<TmeOutstockinfo> selectPage(TmeOutstockinfoCriteria example);

    Integer selectMaxPrimaryKeyValue();
}