package com.shinowit.dao.mapper;

import com.shinowit.entity.TmeOrderdetailsinfo;
import com.shinowit.entity.TmeOrderdetailsinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmeOrderdetailsinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderDetailsInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    int countByExample(TmeOrderdetailsinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderDetailsInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    int deleteByExample(TmeOrderdetailsinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderDetailsInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderDetailsInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    int insert(TmeOrderdetailsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderDetailsInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    int insertSelective(TmeOrderdetailsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderDetailsInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    List<TmeOrderdetailsinfo> selectByExample(TmeOrderdetailsinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderDetailsInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    TmeOrderdetailsinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderDetailsInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    int updateByExampleSelective(@Param("record") TmeOrderdetailsinfo record, @Param("example") TmeOrderdetailsinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderDetailsInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    int updateByExample(@Param("record") TmeOrderdetailsinfo record, @Param("example") TmeOrderdetailsinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderDetailsInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    int updateByPrimaryKeySelective(TmeOrderdetailsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderDetailsInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    int updateByPrimaryKey(TmeOrderdetailsinfo record);

    List<TmeOrderdetailsinfo> selectPage(TmeOrderdetailsinfoCriteria example);

    Integer selectMaxPrimaryKeyValue();
}