package com.shinowit.entity;

import java.io.Serializable;

public class TbaDeliveryinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_DeliveryInfo.DeliveryID
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    private String deliveryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_DeliveryInfo.Address
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_DeliveryInfo.DeliveryName
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    private String deliveryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_DeliveryInfo.Email
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_DeliveryInfo.ID
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_DeliveryInfo.LinkName
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    private String linkname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_DeliveryInfo.LinkTel
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    private String linktel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_DeliveryInfo.QQ
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_DeliveryInfo.SortID
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    private Short sortid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_DeliveryInfo.State
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_DeliveryInfo.DeliveryID
     *
     * @return the value of TBa_DeliveryInfo.DeliveryID
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public String getDeliveryid() {
        return deliveryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_DeliveryInfo.DeliveryID
     *
     * @param deliveryid the value for TBa_DeliveryInfo.DeliveryID
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public void setDeliveryid(String deliveryid) {
        this.deliveryid = deliveryid == null ? null : deliveryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_DeliveryInfo.Address
     *
     * @return the value of TBa_DeliveryInfo.Address
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_DeliveryInfo.Address
     *
     * @param address the value for TBa_DeliveryInfo.Address
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_DeliveryInfo.DeliveryName
     *
     * @return the value of TBa_DeliveryInfo.DeliveryName
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public String getDeliveryname() {
        return deliveryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_DeliveryInfo.DeliveryName
     *
     * @param deliveryname the value for TBa_DeliveryInfo.DeliveryName
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public void setDeliveryname(String deliveryname) {
        this.deliveryname = deliveryname == null ? null : deliveryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_DeliveryInfo.Email
     *
     * @return the value of TBa_DeliveryInfo.Email
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_DeliveryInfo.Email
     *
     * @param email the value for TBa_DeliveryInfo.Email
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_DeliveryInfo.ID
     *
     * @return the value of TBa_DeliveryInfo.ID
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_DeliveryInfo.ID
     *
     * @param id the value for TBa_DeliveryInfo.ID
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_DeliveryInfo.LinkName
     *
     * @return the value of TBa_DeliveryInfo.LinkName
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public String getLinkname() {
        return linkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_DeliveryInfo.LinkName
     *
     * @param linkname the value for TBa_DeliveryInfo.LinkName
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public void setLinkname(String linkname) {
        this.linkname = linkname == null ? null : linkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_DeliveryInfo.LinkTel
     *
     * @return the value of TBa_DeliveryInfo.LinkTel
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public String getLinktel() {
        return linktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_DeliveryInfo.LinkTel
     *
     * @param linktel the value for TBa_DeliveryInfo.LinkTel
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public void setLinktel(String linktel) {
        this.linktel = linktel == null ? null : linktel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_DeliveryInfo.QQ
     *
     * @return the value of TBa_DeliveryInfo.QQ
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_DeliveryInfo.QQ
     *
     * @param qq the value for TBa_DeliveryInfo.QQ
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_DeliveryInfo.SortID
     *
     * @return the value of TBa_DeliveryInfo.SortID
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public Short getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_DeliveryInfo.SortID
     *
     * @param sortid the value for TBa_DeliveryInfo.SortID
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public void setSortid(Short sortid) {
        this.sortid = sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_DeliveryInfo.State
     *
     * @return the value of TBa_DeliveryInfo.State
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_DeliveryInfo.State
     *
     * @param state the value for TBa_DeliveryInfo.State
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbaDeliveryinfo other = (TbaDeliveryinfo) that;
        return (this.getDeliveryid() == null ? other.getDeliveryid() == null : this.getDeliveryid().equals(other.getDeliveryid()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getDeliveryname() == null ? other.getDeliveryname() == null : this.getDeliveryname().equals(other.getDeliveryname()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLinkname() == null ? other.getLinkname() == null : this.getLinkname().equals(other.getLinkname()))
            && (this.getLinktel() == null ? other.getLinktel() == null : this.getLinktel().equals(other.getLinktel()))
            && (this.getQq() == null ? other.getQq() == null : this.getQq().equals(other.getQq()))
            && (this.getSortid() == null ? other.getSortid() == null : this.getSortid().equals(other.getSortid()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_DeliveryInfo
     *
     * @mbggenerated Sun Jan 04 23:42:59 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDeliveryid() == null) ? 0 : getDeliveryid().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getDeliveryname() == null) ? 0 : getDeliveryname().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLinkname() == null) ? 0 : getLinkname().hashCode());
        result = prime * result + ((getLinktel() == null) ? 0 : getLinktel().hashCode());
        result = prime * result + ((getQq() == null) ? 0 : getQq().hashCode());
        result = prime * result + ((getSortid() == null) ? 0 : getSortid().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        return result;
    }
}